CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    accesses INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
)